export const icons = {
    home: require('@/assets/icons/home.png'),
    bookmark: require('@/assets/icons/bookmark.png'),
    "eye-hide": require('@/assets/icons/eye-hide.png'),
    eye: require('@/assets/icons/eye.png'),
    "left-arrow": require('@/assets/icons/left-arrow.png'),
    logout: require('@/assets/icons/logout.png'),
    menu: require('@/assets/icons/menu.png'),
    play: require('@/assets/icons/play.png'),
    plus: require('@/assets/icons/plus.png'),
    profile: require('@/assets/icons/profile.png'),
    "right-arrow": require('@/assets/icons/right-arrow.png'),
    search: require('@/assets/icons/search.png'),
    upload: require('@/assets/icons/upload.png'),
}