export const icons = {
    home: require('./home.png'),
    bookmark: require('./bookmark.png'),
    "eye-hide": require('./eye-hide.png'),
    eye: require('./eye.png'),
    "left-arrow": require('./left-arrow.png'),
    logout: require('./logout.png'),
    menu: require('./menu.png'),
    play: require('./play.png'),
    plus: require('./plus.png'),
    profile: require('./profile.png'),
    "right-arrow": require('./right-arrow.png'),
    search: require('./search.png'),
    upload: require('./upload.png'),
}